spring.application.name=video-chat-backend

spring.datasource.url=jdbc:mysql://localhost:3306/video_chat_app
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=localhost
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}